name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn test

    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: java-app
        path: target/*.war

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: java-app

    - name: Deploy to Jenkins
      run: |
        CRUMB=$(curl -u "$JENKINS_USER:$JENKINS_API_TOKEN" "$JENKINS_URL/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)")
        curl -X POST -u "$JENKINS_USER:$JENKINS_API_TOKEN" -H "$CRUMB" "$JENKINS_URL/job/$JENKINS_JOB_NAME/buildWithParameters?artifact=target/*.war"
      env:
        JENKINS_URL: ${{ secrets.JENKINS_URL }}
        JENKINS_JOB_NAME: ${{ secrets.JENKINS_JOB_NAME }}
        JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}

    - name: Notify deployment success
      run: echo "Deployment to Tomcat via Jenkins was successful!"
